// src/components/ResultCard.jsx
import React from "react";
import { motion } from "framer-motion";
import jsPDF from "jspdf";

export default function ResultCard({ data }) {
  const isApproved = data.status === "APPROVED";

  const handleDownload = () => {
    const doc = new jsPDF();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("Invoice & PO Matching Result", 20, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Invoice Number: ${data.invoice_number || "N/A"}`, 20, 40);
    doc.text(`PO Number: ${data.po_number || "N/A"}`, 20, 50);
    doc.text(`Status: ${data.status}`, 20, 60);
    doc.text(`Vendor Match: ${data.vendor_match ? "Yes" : "No"}`, 20, 70);
    doc.text(`Total Amount Match: ${data.total_match ? "Yes" : "No"}`, 20, 80);

    if (data.issues && data.issues.length > 0) {
      doc.text("Issues Found:", 20, 95);
      data.issues.forEach((issue, index) => {
        doc.text(`• ${issue}`, 25, 105 + index * 10);
      });
    }

    doc.text("Generated by Invoice Matcher", 20, 140);
    doc.save(`matching-result-${data.invoice_number || "result"}.pdf`);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45 }}
      className={`mt-4 rounded-xl p-6 shadow-xl border-l-4 ${
        isApproved ? "bg-green-50 border-green-400" : "bg-red-50 border-red-400"
      }`}
    >
      <div className="flex flex-col gap-4">
        <div className="flex items-start gap-4">
          <div className="text-4xl font-bold" aria-hidden>
            {isApproved ? "✓" : "✗"}
          </div>

          <div>
            <h4
              className={`text-2xl font-extrabold ${
                isApproved ? "text-green-700" : "text-red-700"
              }`}
            >
              {isApproved ? "APPROVED" : "MISMATCH"}
            </h4>
            <p className="text-slate-700 mt-2">
              Matching result for Invoice{" "}
              <strong>{data.invoice_number || "N/A"}</strong> and PO{" "}
              <strong>{data.po_number || "N/A"}</strong>.
            </p>

            <div className="mt-4 space-y-2 text-slate-800">
              <div>
                <strong>Vendor Match:</strong>{" "}
                {data.vendor_match ? "✓ Yes" : "✗ No"}
              </div>
              <div>
                <strong>Total Amount Match:</strong>{" "}
                {data.total_match ? "✓ Yes" : "✗ No"}
              </div>
              {data.issues && data.issues.length > 0 && (
                <div className="mt-2">
                  <strong>Issues Found:</strong>
                  <ul className="list-disc list-inside mt-1 text-sm">
                    {data.issues.map((it, i) => (
                      <li key={i}>{it}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="flex justify-end">
          <button
            onClick={handleDownload}
            className="mt-4 bg-blue-600 text-white font-semibold px-5 py-2 rounded-lg shadow-md hover:bg-blue-700"
          >
            Download Result
          </button>
        </div>
      </div>
    </motion.div>
  );
}
